apiVersion: nodeobservability.olm.openshift.io/v1alpha1
kind: NodeObservability
metadata:
  name: cluster
spec:
  labels:
    node-role.kubernetes.io/worker: ""
  image: "registry.ci.openshift.org/ocp/4.11:node-observability-agent"
  type: crio-kubelet
