apiVersion: nodeobservability.olm.openshift.io/v1alpha2
kind: NodeObservabilityRun
metadata:
  name: nodeobservabilityrun-sample
  namespace: node-observability-operator
spec:
  nodeObservabilityRef:
    name: cluster
