apiVersion: nodeobservability.olm.openshift.io/v1alpha1
kind: NodeObservabilityMachineConfig
metadata:
  name: nodeobservabilitymachineconfig-sample
spec:
  enableCrioProfiling: true
  enableKubeletProfiling: true
